### ISSUE TITLE
How to build a static library?

### ISSUE THREAD

**Issue by cocomeIon** [nyorain/swa#1]
Including a single file would be even better.

**Comment by nyorain** [comment]
Building with meson's `--default-library=static` should work to get a static library (tested on linux, haven't tested that on windows for a while though). Feel free to just copy together all the implementation you need into a single file but since that would make coding swa worse (adding a lot of `#ifdef`s), the implementation will remain separate.

**Comment by cocomeIon** [comment]
Compiled. Now need to make dlg static because it can't find it.
